### ISSUE TITLE
你好，你能留一下你的邮箱呢？

### ISSUE THREAD

**Issue by mymuli** [sorrowyn/MGTN#1]
你好，你可以留一下你的邮箱呢？有几个问题，想跟你讨论一下...

**Comment by sorrowyn** [comment]
你留下你的邮箱，我加你

**Comment by sorrowyn** [comment]
> 
> 
> 你好，你可以留一下你的邮箱呢？有几个问题，想跟你讨论一下...

你留下你的邮箱，我加你

**Comment by mymuli** [comment]
我邮箱是 ***@***.***




| |
mymuli
|
|
***@***.***
|

Signature is customized by Netease Mail Master

在2021年04月23日 14:35，水鱼鱼水 写道：

你好，你可以留一下你的邮箱呢？有几个问题，想跟你讨论一下...

你留下你的邮箱，我加你
